server:
  port: 8091
  servlet:
    context-path: /api/public-info
management:
  server:
    port: 8190
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: secretpassword
  liquibase:
    default-schema: public_bank_information
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false
  application:
    name: public-info-app
#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    prefer-ip-address: true
